package org.oop2023.utils;

public class CharMapMethods {
    public static int encode(char ch) {
        switch (ch) {
            case 'A':
            case 'a':
                return 1;
            case 'À':
            case 'à':
                return 2;
            case 'Á':
            case 'á':
                return 3;
            case 'Ả':
            case 'ả':
                return 4;
            case 'Ã':
            case 'ã':
                return 5;
            case 'Ạ':
            case 'ạ':
                return 6;
            case 'Ă':
            case 'ă':
                return 7;
            case 'Ằ':
            case 'ằ':
                return 8;
            case 'Ắ':
            case 'ắ':
                return 9;
            case 'Ẳ':
            case 'ẳ':
                return 10;
            case 'Ẵ':
            case 'ẵ':
                return 11;
            case 'Ặ':
            case 'ặ':
                return 12;
            case 'Â':
            case 'â':
                return 13;
            case 'Ầ':
            case 'ầ':
                return 14;
            case 'Ấ':
            case 'ấ':
                return 15;
            case 'Ẩ':
            case 'ẩ':
                return 16;
            case 'Ẫ':
            case 'ẫ':
                return 17;
            case 'Ậ':
            case 'ậ':
                return 18;
            case 'B':
            case 'b':
                return 19;
            case 'C':
            case 'c':
                return 20;
            case 'D':
            case 'd':
                return 21;
            case 'Đ':
            case 'đ':
                return 22;
            case 'E':
            case 'e':
                return 23;
            case 'È':
            case 'è':
                return 24;
            case 'É':
            case 'é':
                return 25;
            case 'Ẻ':
            case 'ẻ':
                return 26;
            case 'Ẽ':
            case 'ẽ':
                return 27;
            case 'Ẹ':
            case 'ẹ':
                return 28;
            case 'Ê':
            case 'ê':
                return 29;
            case 'Ề':
            case 'ề':
                return 30;
            case 'Ế':
            case 'ế':
                return 31;
            case 'Ể':
            case 'ể':
                return 32;
            case 'Ễ':
            case 'ễ':
                return 33;
            case 'Ệ':
            case 'ệ':
                return 34;
            case 'F':
            case 'f':
                return 35;
            case 'G':
            case 'g':
                return 36;
            case 'H':
            case 'h':
                return 37;
            case 'I':
            case 'i':
                return 38;
            case 'Ì':
            case 'ì':
                return 39;
            case 'Í':
            case 'í':
                return 40;
            case 'Ỉ':
            case 'ỉ':
                return 41;
            case 'Ĩ':
            case 'ĩ':
                return 42;
            case 'Ị':
            case 'ị':
                return 43;
            case 'J':
            case 'j':
                return 44;
            case 'K':
            case 'k':
                return 45;
            case 'L':
            case 'l':
                return 46;
            case 'M':
            case 'm':
                return 47;
            case 'N':
            case 'n':
                return 48;
            case 'O':
            case 'o':
                return 49;
            case 'Ò':
            case 'ò':
                return 50;
            case 'Ó':
            case 'ó':
                return 51;
            case 'Ỏ':
            case 'ỏ':
                return 52;
            case 'Õ':
            case 'õ':
                return 53;
            case 'Ọ':
            case 'ọ':
                return 54;
            case 'Ô':
            case 'ô':
                return 55;
            case 'Ồ':
            case 'ồ':
                return 56;
            case 'Ố':
            case 'ố':
                return 57;
            case 'Ổ':
            case 'ổ':
                return 58;
            case 'Ỗ':
            case 'ỗ':
                return 59;
            case 'Ộ':
            case 'ộ':
                return 60;
            case 'Ơ':
            case 'ơ':
                return 61;
            case 'Ờ':
            case 'ờ':
                return 62;
            case 'Ớ':
            case 'ớ':
                return 63;
            case 'Ở':
            case 'ở':
                return 64;
            case 'Ỡ':
            case 'ỡ':
                return 65;
            case 'Ợ':
            case 'ợ':
                return 66;
            case 'P':
            case 'p':
                return 67;
            case 'Q':
            case 'q':
                return 68;
            case 'R':
            case 'r':
                return 69;
            case 'S':
            case 's':
                return 70;
            case 'T':
            case 't':
                return 71;
            case 'U':
            case 'u':
                return 72;
            case 'Ù':
            case 'ù':
                return 73;
            case 'Ú':
            case 'ú':
                return 74;
            case 'Ủ':
            case 'ủ':
                return 75;
            case 'Ũ':
            case 'ũ':
                return 76;
            case 'Ụ':
            case 'ụ':
                return 77;
            case 'Ư':
            case 'ư':
                return 78;
            case 'Ừ':
            case 'ừ':
                return 79;
            case 'Ứ':
            case 'ứ':
                return 80;
            case 'Ử':
            case 'ử':
                return 81;
            case 'Ữ':
            case 'ữ':
                return 82;
            case 'Ự':
            case 'ự':
                return 83;
            case 'V':
            case 'v':
                return 84;
            case 'W':
            case 'w':
                return 85;
            case 'X':
            case 'x':
                return 86;
            case 'Y':
            case 'y':
                return 87;
            case 'Ỳ':
            case 'ỳ':
                return 88;
            case 'Ý':
            case 'ý':
                return 89;
            case 'Ỷ':
            case 'ỷ':
                return 90;
            case 'Ỹ':
            case 'ỹ':
                return 91;
            case 'Ỵ':
            case 'ỵ':
                return 92;
            case 'Z':
            case 'z':
                return 93;
            case '\'':
                return 94;
            case '-':
                return 95;
            case '0':
                return 96;
            case '1':
                return 97;
            case '2':
                return 98;
            case '3':
                return 99;
            case '4':
                return 100;
            case '5':
                return 101;
            case '6':
                return 102;
            case '7':
                return 103;
            case '8':
                return 104;
            case '9':
                return 105;
            case ' ':
                return 106;
            default:
                return 0;
        }
    }

    public static char decode(int code) {
        switch(code) {
            case 1:
                return 'a';
            case 2:
                return 'à';
            case 3:
                return 'á';
            case 4:
                return 'ả';
            case 5:
                return 'ã';
            case 6:
                return 'ạ';
            case 7:
                return 'ă';
            case 8:
                return 'ằ';
            case 9:
                return 'ắ';
            case 10:
                return 'ẳ';
            case 11:
                return 'ẵ';
            case 12:
                return 'ặ';
            case 13:
                return 'â';
            case 14:
                return 'ầ';
            case 15:
                return 'ấ';
            case 16:
                return 'ẩ';
            case 17:
                return 'ẫ';
            case 18:
                return 'ậ';
            case 19:
                return 'b';
            case 20:
                return 'c';
            case 21:
                return 'd';
            case 22:
                return 'đ';
            case 23:
                return 'e';
            case 24:
                return 'è';
            case 25:
                return 'é';
            case 26:
                return 'ẻ';
            case 27:
                return 'ẽ';
            case 28:
                return 'ẹ';
            case 29:
                return 'ê';
            case 30:
                return 'ề';
            case 31:
                return 'ế';
            case 32:
                return 'ể';
            case 33:
                return 'ễ';
            case 34:
                return 'ệ';
            case 35:
                return 'f';
            case 36:
                return 'g';
            case 37:
                return 'h';
            case 38:
                return 'i';
            case 39:
                return 'ì';
            case 40:
                return 'í';
            case 41:
                return 'ỉ';
            case 42:
                return 'ĩ';
            case 43:
                return 'ị';
            case 44:
                return 'j';
            case 45:
                return 'k';
            case 46:
                return 'l';
            case 47:
                return 'm';
            case 48:
                return 'n';
            case 49:
                return 'o';
            case 50:
                return 'ò';
            case 51:
                return 'ó';
            case 52:
                return 'ỏ';
            case 53:
                return 'õ';
            case 54:
                return 'ọ';
            case 55:
                return 'ô';
            case 56:
                return 'ồ';
            case 57:
                return 'ố';
            case 58:
                return 'ổ';
            case 59:
                return 'ỗ';
            case 60:
                return 'ộ';
            case 61:
                return 'ơ';
            case 62:
                return 'ờ';
            case 63:
                return 'ớ';
            case 64:
                return 'ở';
            case 65:
                return 'ỡ';
            case 66:
                return 'ợ';
            case 67:
                return 'p';
            case 68:
                return 'q';
            case 69:
                return 'r';
            case 70:
                return 's';
            case 71:
                return 't';
            case 72:
                return 'u';
            case 73:
                return 'ù';
            case 74:
                return 'ú';
            case 75:
                return 'ủ';
            case 76:
                return 'ũ';
            case 77:
                return 'ụ';
            case 78:
                return 'ư';
            case 79:
                return 'ừ';
            case 80:
                return 'ứ';
            case 81:
                return 'ử';
            case 82:
                return 'ữ';
            case 83:
                return 'ự';
            case 84:
                return 'v';
            case 85:
                return 'w';
            case 86:
                return 'x';
            case 87:
                return 'y';
            case 88:
                return 'ỳ';
            case 89:
                return 'ý';
            case 90:
                return 'ỷ';
            case 91:
                return 'ỹ';
            case 92:
                return 'ỵ';
            case 93:
                return 'z';
            case 94:
                return '\'';
            case 95:
                return '-';
            case 96:
                return '0';
            case 97:
                return '1';
            case 98:
                return '2';
            case 99:
                return '3';
            case 100:
                return '4';
            case 101:
                return '5';
            case 102:
                return '6';
            case 103:
                return '7';
            case 104:
                return '8';
            case 105:
                return '9';
            case 106:
                return ' ';
            default:
                return '?';
        }
    }
}
